# Marco Teórico

## Apoyo a un Líder Fuerte


Se entenderá el apoyo a un Líder Fuerte como la demanda, por parte de los ciudadanos, de que el poder político este concentrado en un líder, ejerciendolo de manera personalista, con poco o nulo contrapeso por parte de otras instituciones o actores. Pese a que este tipo de liderazgos se han considerado como más comunes en en regímenes autoritarios [@kendall-taylor2017], durante las últimas décadas se ha observado su auge también en democracias liberales consolidadas [@lindstaedt2021; @kendall-taylor2017]. 

Se ha propuesto que este tipo de liderazgo tiene mayores posibilidades de aparecer en contextos negativos o de incertidumbre, donde un líder fuerte suele ser precibido como una solución a problemas políticos o económicos [@harms2018]. El ascenso al poder de este tipo de líderes se ha asociado a mayor polarización, concentración del poder y, a largo plazo, deterioro democrático [@lindstaedt2021; @brunkert2023; @kendall-taylor2017]. Pese a ello, el apoyo a este tipo de liderazgo ha crecido a lo largo del mundo, y una parte importante de la literatura se ha dedicado a comprender los factores de esta tendencia. Entre algunas explicaciones que se han esbozado se cuentan rasgos de la personalidad como la mentalidad cerrada o la introversión (@armendarizmiranda2021), la incertidumbre identitaria [@hogg2021; @hogg2013], el deseo por continuar la identidad nacional [@selvanathan2022], la desigualdad económica (@sprong2019) y la baja confianza interpersonal [@xuereb2021].

Además, se ha indicado que el apoyo a un líder fuerte se encuentra asociado a la llamda personalidad autoritaria [@harms2018]. Particularmente, los autoritarios estarían más dispuestos a renunciar a su autonomía personal frente a un autoridades percibidas como poderosas [@harms2018). En la misma linea, se ha planteado que el individualismo no es tanto el opuesto al colectivismo, sino del autoritarismo [@gelfand1996). De tal modo, existe una tendencia en la literatura a asociar negativamente al individualismo con actitudes autoritarias, planteando más bien una relación con el apoyo a las variantes más liberales y representativas de democracia. Pese a ello, también se ha encontrado evidencia empírica que apunta a la asociación entre el individualismo con el conservadurismo [@zhang2009], el autoritarismo [@kemmelmeier2003] y la dominancia social [@strunk1999]. De tal modo, el panorama general sugiere que la relación entre individualismo y democracia está lejos de ser unívoca.

Frente a lo anterior, en la siguiente sección se presentará la propuesta teórica de esta investigación. La apuesta aquí es que la sociología del individuo entregaría las herramientas necesarias para comprender las relaciones divergentes entre el individualismo y los tipos de liderazgos por la ciudadanía. 

## Individualismo

El fenómeno del individualismo ha sido principalmente investigado desde la psicología cultural, con un enfoque especial en la comparación entre distintas culturas. Desde esta perspectiva, de tal modo, se tienden a categorizar culturas (y, se debe notar, cultura se entiende casi siempre como sinónimo de país), ya sea como individualistas o como colectivistas. Las sociedades individualistas se caracterizarían por lazos poco estrechos entre individuos, de quienes se espera se hagan cargo de sí mismos y de su familia inmediata. Las sociedades colectivistas, en tanto, se definen porque sus miembros están integrados desde su nacimiento a grupos fuertemente cohesionados que los protegen a lo largo de sus vidas a cambio de una lealtad incuestionable [@yoon2010]. 

Esta conceptualización de individualismo-colectivismo ha sido criticado por su falta de claridad conceptual [@oyserman2002], calificándolo como un concepto *catch-all*, que se utiliza por defecto para explicar diferencias culturales [@voronov2002] y que esconde un dimensión normativa que asocia el individualismo a la modernidad y al desarrollo [@voronov2002; @wang2010; @martuccelli2010; @moemeka1998]. Brewer y Chen [-@brewer2007] además, indican que no hay una verdadera simetría en la forma en que se operacionalizan el individualismo y el colectivismo, pues, mientras que los ítems utilizados para medir el individualismo suelen centrarse en la identidad y la agencia de los individuos, el colectivismo se suele medir como un sistema de valores.

Estas limitaciones se expresan en "anomalías" observables en varios de estos estudios, como que los individualistas pueden ser tanto o más colectivistas que los colectivistas mismos [@oyserman2002], o que en determinados contextos los colectivistas actúan de manera individualista [@voronov2002]. A nivel agregado, Chile podría considerarse como un claro ejemplo de estas contradicciones: Bajo la definición de Hofstede, la sociedad chilena ha sido clasificada como colectivista [@rojas2008]. Esto concuerda con observaciones que han señalado que el colectivismo en Chile es alto, tanto si se mide como el opuesto al individualismo [@oyserman2002] o entendido como un *self-construal* interdependiente [@benavides2020]. No obstante, también es cierto que los niveles de individualismo observados en el país llegan a ser incluso más altos que aquellos obtenidos en sociedades típicamente individualistas, como Estados Unidos [@oyserman2002] o Noruega [@kolstad2009].

Esto abre la pregunta de si Chile realmente es una sociedad colectivista, y si no lo es, ¿hasta qué punto es una sociedad individualista? La propuesta de esta investigación es que, con el fin de responder esta pregunta, es necesario dar un giro hacia una perspectiva teórica que provea el lenguaje para describir el individualismo chileno. En concreto, se conceptualizará el individualismo desde la sociología del individuo desarrollada por Danilo Martuccelli. Desde este enfoque, tanto en su obra individual [@martuccelli2010; @martuccelli2018], como en colaboración con Kathya Araujo [@araujo2014; @araujo2020; @araujo2012], Martuccelli ha hecho esfuerzos contundentes para describir la forma particular del individualismo en Chile y América Latina. 

Martuccelli [-@martuccelli2010] argumenta que la representación del individuo que se volvió hegemónica para la modernidad es un individuo que es soberano en al menos dos acepciones. En primer lugar, porque se espera de este que sea dueño de sí mismo, de manera independiente, autónoma y singular. En segundo lugar, porque es un ente racional capaz de legitimar el orden social y la soberanía colectiva.

Este individuo se encuentra en el vértice de un modelo de representación de la vida social que lo sitúa en el centro del pacto social [@martuccelli2010; @martuccelli2018]. Este modelo es lo que comúnmente se entiende como individualismo. Martuccelli [-@martuccelli2018] denomina a esta variante del fenómeno como *individualismo institucional*, caracterizado por una separación readical entre holismo e individualsimo, una concepción atomizada del individuo y la preminencia del rol de las instituciones en los procesos de individuación. 

Las divergencias respecto a este modelo, observadas en otras regiones del mundo, a menudo ha llevado de la negación existencia de individuos, individualización e individualismo en éstas [@martuccelli2010]. En cambio, abordar el fenómeno del individualismo desde la sociología del individuo permite desembarazarse de estas conceptualizaciones unívocas. Frente a ello, se propone una definición que permita teorizar el fenómeno para la sociedad chilena.

Se entenderá así como individualismo a los modelos de representación de la vida social que definen el rol del individuo en la sociedad. Bajo tales modelos, los individuos deben hacerse cargo de sus propias vidas en condiciones diversas de a) legitimidad de la acción individual, b) distintas representaciones culturales y autoconcepciones del individuo, y c) diferentes valores e imperativos estructuralmente producidos.

**La legitimidad de la acción individual** hace referencia  a las creencias sobre la agencia de los individuos en el mundo social [@brewer2007] y la legitimidad de acciones individualizadas en las esferas de la economía, la política y las emociones [@cortois2018]. Una mayor legitimidad de la acción individual se relaciona a una mayor valoración de la individualidad, la cual se define como el "grado de diferenciación o de singularización reconocido o legítimamente alcanzado por un individuo dentro de un colectivo" [@martuccelli2018, p. 10].

Bajo el modelo del individualismo institucional, la individualidad deja de ser una anomalía para pasar a ostentar altos niveles de legitimidad [@martuccelli2018]. Sin embargo, esto se vería tensionado, por ejemplo, por la acentuación de conductas individualizadas sin ruptura de lazos comunitarios en sociedadades africanas, modelo que Martuccelli [-@martuccelli2018] denomina como individualismo comunitario. Más cercano a la realidad nacional, Araujo y Martuccelli [-@araujo2020a] constatan que la individualidad ha sido históricamente vista con sospecha en sociedades latinoamericanas.

Ahora bien, se debe resaltar que el individualismo ha sido institucionalizado principalmente en 3 esferas: la económica, la política y la afectiva [@cortois2018; @martuccelli2018]. Esto se refleja en la existencia de 3 guiones para el individualismo institucional; en la esfera económica, un individualismo utilitario que legitima la acción individual estratégica, poniendo medio sobre fines; en la política, un individualismo moral que enfatiza la obligación de tratar al otro como un fin en sí mismo; y en la afectiva, un individualismo expresivo en que la acción social se entiende como un medio para la expresión auténtica del yo [@cortois2018]. 

**Las autoconcepciones del individuo**, por otro lado, abordan las diversas concepciones en torno a las que se pueden definir las identidades de los individuos en relación a sus grupos de referencia [@brewer2007].

La concepción independiente es aquella en que el individuo se concibe como un ente atomizado y prexistente a sus lazos sociales. Aunque esta concepción se ha considerado como propia de las culturas individualistas [@benavides2020; @cross2011], tal idea ha sido problematizada teórica [@voronov2002] y empíricamente [@benavides2020; @kolstad2009]. Además, la persistencia de los llamados valores asiáticos en esas sociedades, que conceptualizan al individuo como inseparable de sus lazos sociales [@zhai2022], y la conceptualización de un híper-actor relacional en la sociedad chilena [@araujo2020], sugieren la posibilidad de individualismos que difieren de las concepciones independientes. 

De tal modo, se podrían identificar, además, concepciones relacionales y concepciones colectivas [@brewer2007]. En las primeras, la identidad del individuo se define por sus relaciones cercanas, tales como la familia o los amigos. En las segundas, en tanto, es la pertenencia a colectivos sociales más abstractos -- esto es, grupos nacionales, regionales, étnicos o religiosos -- lo que define a la identidad individual [@brewer2007]

Por último, la tercera dimensión del individualismo se refiere a la importancia relativa que se le otorga en una sociedad a diversos **valores e imperativos** individuales o colectivos [@brewer2007], los cuales son producidos por procesos sociohistóricos de individuación [@martuccelli2018]. En el contexto del individualismo institucional, el principal valor para el individuo es la autonomía [@martuccelli2010], la que es promovida a través de un entramado institucional [@martuccelli2018] que promueve que los individuos se constituyen a sí mismos, planifique su propia vida y acepten la responsabilidad de si fracasan [@robles2001]. Es, pues, una individuación reflexiva en la que los individuos se definen por el imperativo de ejercer control de sus destinos y tomar decisiones de manera autónoma [@silvapalacios2015; @robles2001]. 

Sin embargo, también se han planteado visiones críticas a esta concepción, particularmente desde América Latina [@araujo2012; @robles2001]. No toda individuación sería reflexiva, ya que muchos individuos podrían experimentarla de forma delegativa, como una imposición [@silvapalacios2015]; no como un mundo de posibilidades, sino como uno lleno de incertidumbres. Los individuos, de tal modo, deben enfrentar las inseguridades ontológicas de la vida social a partir de sus propias habilidades bajo el imperativo de "arréglatelas como puedas" [@araujo2014; @robles2001]. Frente a esto, la valorización de la autonomía se desplaza por la búsqueda de seguridad como valor principal de esta forma de individuación [@silvapalacios2015].

## Hipótesis de trabajo

Lo que se desea resaltar aquí es la existencia de diversos perfiles de individualismo que emergen de distintas combinaciones de las dimensiones previamente mencionadas. Estos perfiles no solo difieren entre culturas, sino también dentro de una misma sociedad, como resultado de procesos de individuación divergentes que afectan de manera diferenciada distintos segmentos de la población. 

La individuación es una corriente histórica y estructural, que entre sus efectos, transforma la relación de los individuos con la autoridad, así como los soportes y las modalidades que autorizan su ejercicio [@araujo2021]. Si a esto se le añade la evidencia empórica que apunta a la asociación entre el individualismo y el conservadurismo [@zhang2009], el autoritarismo [@kemmelmeier2003] y la dominancia social [@strunk1999], el panorama general sugiere que la relación entre individualismo y democracia está lejos de ser unívoca. 

De tal forma, la hipótesis de trabajo que guía esta investigación es que las divergencias en los procesos de individuación, que tienen por resultado diversos perfiles de individualismo, se asocian a diferencias en las preferencias políticas. Así, en algunos casos estos procesos  condujeron a modelos institucionales de individualismo, donde el individuo se convierte en un soberano que legitima un orden social liberal y democrático. Sin embargo, en otros casos, los resultados de los procesos de individuación pueden dar lugar a variantes de individualismo en las que los individuos podrían preferir formas de autoridad que se alejan del ideal representativo de la democracia, apoyando liderazgos fuertes que pasen por sobre el control de otras instituciones. 

