# Discusión

**Apoyo a la Líderes Fuertes**

Según datos de la Encuesta Mundial de Valores, el 44% de la población chilena consideraría como bueno o muy buena contar con un líder fuerte que no le importen el congreso o las elecciones. Si bien esta cifra puede considerarse como baja en el contexto latinoamericano, donde los niveles de apoyo a un líder fuerte se encuentran sobre el 50% en prácticamente todos los países de la región sondeados, se debe destacar una tendencia al alza sostenida entre el 2006 y el 2018, creciendo 12 puntos porcentuales en ese período.

Los datos que pueda entregar la Octava Ola de la Encuesta Mundial de Valores, que debieran estar disponibles a más tardar en 2026, van a ser interesantes para constatar si esta tendencia ha continuado durante el último lustro. Al respecto, es importantes destacar que los datos disponibles son anteriores a fenómenos sociales de gran importancia que podrían influir en como los ciudadanos evalúan este tipo de líderes, como el Estallido Social del 2019, la pandemia por COVID-19, la crisis migratoria y de seguridad, así como la irrupción de liderazgos autoritarios tanto en el contexto nacional como latinoamericano.

**Perfiles de Individualismo**

El análisis de clases latentes realizado respalda la hipótesis de que los procesos de individualización divergen dentro de una misma sociedad. A partir de los datos examinados, se logró identificar cuatro perfiles distintos de individualismo en la sociedad chilena: individualismo autoritario, individualismo conservador, individualismo liberal e individualismo agéntico. Cada uno de estos perfiles equivale a variadas representaciones de la posición del individuo en la sociedad, y son resultado de combinaciones específicas de legitimidad de la acción individual en diferentes esferas, concepciones variadas del individuo, y diferentes valores e imperativos estructuralmente producidos. Además, la presencia de diferencias en edad, orientación política, ubicación geográfica o afiliación religiosa entre estos perfiles arroja luz sobre cómo los procesos estructurales interactúan de manera diferenciada con distintos segmentos de la población.

La tipología elaborada permite establecer un diálogo con la descripción del individualismo agéntico y el híper-actor relacional propuesto por Araujo y Martuccelli [-@araujo2020]. Este modelo presenta dos características fundamentales: en primer lugar, la confianza depositada en las habilidades personales para afrontar la vida social, y en segundo lugar, la centralidad de las redes interpersonales. Se observó que una de las clases identificadas se acerca de manera más nítida a este modelo, de ahí que se haya decidido mantener la denominación de "individualismo agéntico". No obstante, se debe destacar que los otros perfiles también exhiben rasgos que hacen suponer que comparten, al menos parcialmente, la descripción de Araujo y Martuccelli.

En relación con la confianza en el esfuerzo y las habilidades personales, esto podría observarse en la alta valoración de la competencia y los elevados niveles de independencia observados de manera transversal en todos los perfiles. En términos generales, los datos sugieren que la mayoría de los chilenos cree poseer las habilidades necesarias para asumir el control de sus propias vidas. 

Por otro lado, el carácter relacional del individualismo chileno parece ser una característica que atraviesa todos los perfiles [@araujo2014]. Cierto es que se mide solo una identidad relacional (la familiar) y solo una identidad colectiva (la nacional). Pese a esto, no parece demasiado difícil argumentar la importancia de estas identidades y que incluirlas en el modelo sirve para un buen primer acercamiento.

También es importante señalar que el carácter relacional del individualismo chileno parece no entrar en contradicción con las concepciones independientes, que muestran niveles tan elevados como los indicadores de interdependencia. Esto es consistente tanto con las dos características que describen al individualismo agéntico [@araujo2020] como con las investigaciones sobre el *self-construal* en Chile [@benavides2020; @kolstad2009]. Además, ofrece más respaldo a la idea de que ubicar a Chile en un continuo entre el individualismo y el colectivismo resulta problemático.

En resumen, a partir de los datos analizados, se puede concluir que el individualismo agéntico representa el modelo predominante de individualismo en Chile. Sin embargo, el aporte de esta investigación radica en que, mediante el análisis de clases latentes, es posible observar cómo este modelo diverge dentro de la sociedad chilena. Para algunos, la acción individual debe estar subordinada al orden normativo, mientras que para otros es legítimo actuar de manera estratégica incluso si ello transgrede normas sociales. Mientras que para unos la individualidad tiene cabida en todas las esferas, para otros su legitimidad no alcanza para la esfera afectiva. De tal modo, este enfoque permite observar los matices y las divergencias de los procesos de individualización en Chile. 

**Apoyo a la democracia delegativa y perfiles de individualismo**

El hecho de que haya sido posible establecer una relación estadísticamente significativa entre los perfiles de individualismo y el respaldo a liderazgos fuertes debe ser considerado como una evidencia alentadora del potencial del modelo teórico de individualismo propuesto. Dos de los perfiles identificados muestran una asociación negativa con el apoyar a este tipo de líderes (el conservador y el liberal), mientras que los otros dos (el agéntico y el autoritario) presentan una relación positiva. También es importante destacar que en aquellos que muestran mayores niveles de apoyo son justamente quienes presentaban una menor participación electoral en 2018, en un contexto de voto voluntario. 

Cabe preguntarse si este no es un eje que permita distinguir entre los perfiles identificados: el individualismo conservador y el liberal podrían denominarse como *individualismos cívicos*, orientados hacia lo público. En contraste, el autoritario y el agéntico podrían considerarse más bien *hiperindividualismos*, que están orientados más bien hacia lo privado. En los primeros, la individualidad estaría vinculada a la pertenencia a una comunidad política; en los segundos, lo público representaría un desafío, un obstáculo que se debe evitar ya sea mediante la sumisión de la individualidad a un orden normativo (como en el caso del individualismo autoritario) o mediante la maximización de las habilidades personales (como es el caso del individualismo estratégico). 

Tomando en consideración las diferencias en participación política entre los perfiles, cabe reflexionar sobre las consecuencias de estos hallazgos sobre la democracia chileno, particularmente considerando que ahora los grupos que muestran un mayor apoyo a los líderes fuertes están obligados a votar, en un contexto de crisis de seguridad y en que el denominado "estilo Bukele" empieza a ganar adherentes en el país. 
Si bien otros estudios [@coes2023] han notado la mayor tendencia hacia el autoritarismo y el conservadurismo de los nuevos votantes, cabe preguntarse si es el único fenómeno aquí presente. Normalmente, se ha considerado que la submisión de la autonomía a la autoridad es un rasgo propio de las personalidades autoridades. Si bien esto se observaría en el individualismo autoritario, no es el caso el individualismo estratégico ¿Porque un grupo de la población que valor y legitima la acción individual en todas las esferas estaría predipuesto a liderazgos dominantes? 

Una respuesta se puede encontrar en, como se menciona en la Encuesta Nacional de la Autoridad [@araujo2022], la autoridad política estaría sostenida en la eficacia de los liderazgos para cumplir sus tareas.  Esto en un contexto que Juan Pablo Luna [-@luna2016] ha denominado como "Democracia Desarraigada", donde existe una fuerte desconexión entre ciudadanos y élite política. De tal modo, sería posible hipotetizar que el deseo de los chilenos -- particularmente de los *hiperindividualistas* -- por liderazgos fuertes no es puro autoritarismo, sino la demanda por un tipo de autoridad que se podría denominar como *delegativa* [@odonnell1994]. En una democracia delegativa, los ciudadanos podrían ejercer el voto periódicamente para luego retirarse de la esfera pública hasta la próxima elección [@peruzzotti2008]. Pero esta apatía está lejos de ser un cheque en blanco: al líder electo se le exigen resultados, incluso si ello implica transgredir la autonomía de otras instituciones del Estado. Los hiperindividualistas, así, no estarían -- necesariamente -- en contra de la democracia, pero sí tendrían una visión más pragmática de esta. 

En resumen, esta investigación sugiere que la relación entre el individualismo y el apoyo a lideres fuertes es significativa, pero divergente entre distintos grupos. En otras palabras, distintas formas de individualismos, resultado de divergencias en los procesos de individuación, preferían formas distintas de ejercer la autoridad. Mientras que los individualismos cívicos parecen valorar una visión más representativa de la democracia, los hiperindividualismos favorecen un enfoque más pragmático y apático hacia la esfera pública. Esto ilustra un panorama general en el que las manifestaciones del individualismo, y su relación con otros fenómenos, aparecen como más complejas de lo que otros estudios han propuesto.

# Conclusión

Para cerrar, se presentarán algunas reflexiones sobre las limitaciones y posibles líneas de investigación futuras que se desprenden de este estudio. 

Es importante reflexionar sobre las oportunidades que brinda el análisis de clases latentes en la investigación sobre los procesos de individualización en Chile. Dada la dificultad para traducir su marco teórico a una propuesta metodológica mediante las técnicas cuantitativas más comunes, la sociología del individuo se ha desarrollado principalmente desde una perspectiva cualitativa, resultando en descripciones profundas y estimulantes sobre el individuo en la sociedad chilena. Pese a ello, el enfoque metodológico adoptado en esta investigación permitió identificar algunos de los rasgos del individualismo agéntico descritos por Araujo y Martuccelli [-@araujo2014], al tiempo que ofrece una visión más matizada de cómo los procesos de individuación divergen en la sociedad chilena, diferenciándose entre grupos sociales y teniendo consecuencias en las actitudes políticas de los individuos. 

Por supuesto, enfoques cualitativos y cuantitativos no deben ser vistos como competitivos, sino como complementarios en el desarrollo de una sociología del individuo. Las propias conclusiones aquí delineadas, y las hipótesis que de ellas se desprenden, se verían fuertemente enriquecidas si se incluyeran datos cualitativos que permitirían obtener una compresión más profunda de las distintas variantes de individualismo y su relación divergente con la esfera pública. 

Ahora bien, es necesario reconocer las limitaciones que enfrentó esta investigación. La principal, posiblemente, se derive de los indicadores seleccionados. Aunque los resultados obtenidos parecen prometedores, es crucial continuar avanzando en la construcción y validación de indicadores que permitan traducir el modelo teórico aquí propuesto en un modelo de medición capaz de abordar el fenómeno del individualismo en Chile. En particular, las operacionalizaciones del individualismo utilitario, del individualismo moral, de la interdependencia relacional y de la interdependencia colectiva merecen, sin duda, un mayor trabajo metodológico y conceptual que permitan construir y validar indicadores en esas dimensiones. 

Por otro lado , la recodificación de variables continuas como dicotómicas es una solución pragmática, pero que no deja de ser problemática, ya que resulta en la pérdida de parte de la varianza de los ítems [@fernandes2019]. Futuras investigaciones deberían considerar elaborar indicadores directamente como variables categóricas que no necesiten recodificación para ser incluidas en el modelo de clases latentes. De esta manera, se obtendría claridad en los resultados sin sacrificar información ni poder estadístico.

Otras limitaciones provienen más bien de la muestra. Si 5 años ya se encuentra en el límite de lo que se puede considerar como datos relevantes para la actualidad, a esto se debe sumar que este último lustro ha sido uno particularmente tumultuoso: el Estallido Social, la Pandemia, el proceso constituyente, la crisis migratoria y la crisis de seguridad han sido algunos de los eventos de gran magnitud que han marcado la agenda durante los últimos años. ¿Están hoy los chilenos más dispuestos que hace 5 años a sacrificar su libertad y su individualidad en distintas esferas para obtener garantías de orden y seguridad? Entre las ollas comunes y los retiros de fondos previsionales, entre las protestas masivas y las cuarentenas, ¿cambiaron las concepciones -- independientes, relacionales y colectivas -- con las que los individuos construyen sus identidades? ¿Qué efectos puede tener la instauración del voto obligatorio en el eje individualismo cívico-hiperindividualismo, o en las percepciones de los ciudadanos sobre las formas en que se ejercer la autoridad? Todas estas son preguntas relevantes que quedarán abiertas y deberán ser abordadas en el futuro. 

A su vez, dado que Chile ha participado en 6 olas de la Encuesta Mundial de Valores desde 1990, se debería considerar correr los modelos aquí propuestos utilizando datos de ediciones anteriores (así como estar atento a la próxima versión a realizarse entre 2023 y 2026). Esto permitiría evaluar si los resultados obtenidos en este estudio guardan consistencia con el pasado, así como observar la evolución de estos indicadores a lo largo del tiempo.

Pese a estas limitaciones, el trabajo contenido en este documento logra obtener resultados relevantes. Se encontró evidencia de que distintas formas de individualismo pueden generar actitudes políticas diferentes respecto a los tipos de liderazgos esperados por la ciudadanía. Es importante considerar que estas inclinaciones no surgen en un vacío, sino que son el resultado de la interacción de factores institucionales y estructurales con la agencia de los individuos. De esta manera, se espera que la lectura de esta investigación provoque la reflexión en torno a los tipos de individuos que nuestras instituciones, a través de sus programas e incentivos, contribuyen a producir, así como en las consecuencias de estos procesos para la democracia chilena y la vida social en general. 


 
 
 
 

