# El Individualismo desde la Sociología del Individuo

¿Es Chile una sociedad colectivista? Si no lo es, ¿qué forma adopta el individualismo en la sociedad chilena? Abordar estas preguntas desde la psicología cultural puede conducir —como advierte Martuccelli— a un “relato de la insuficiencia” (“Chile no es un país individualista”) o a un relato del ni-ni (“Chile no es ni individualista ni colectivista”) [@martuccelli2010].

Para escapar de estas trampas y ganar capacidad descriptiva, se propone el giro hacia la sociología del individuo desarrollada por Danilo Martuccelli [@araujo2012; @araujo2014; @araujo2020a; @martuccelli2010; @martuccelli2018]. La ventaja de adoptar esta perspectiva es que ofrece un marco unificador que permite rescatar los aportes de otras disciplinas a la descripción teórica y empírica del individualismo, a la vez que ofrece un lenguaje apropiado para las particularidades del individualismo chileno. 

En esta perspectiva, la modernidad instala una representación hegemónica de un individuo soberano en dos sentidos: (i) dueño de sí —independiente, autónomo, singular— y (ii) capaz de fundamentar el orden social y la soberanía colectiva a partir de su racionalidad. Este individuo se ubica en el centro del pacto social, en lo que Martuccelli denomina individualismo institucional, que se compone de tres características principales [@martuccelli2018]:

i) una separación tajante entre holismo e individualismo, que legitima la individualidad y la acción individual en todas las esferas de la vida social 

ii) Una concepción atomizada de la persona, prexistente a sus lazos sociales

iii) la primacía de las instituciones en los procesos de individuación, poniendo la autonomía como valor primordial de estos procesos. 

Las lecturas se límitan a entender el individualismo como este modelo universal suelen negar la existencia de individuos, individualización o individualismo allí donde el patrón no calza [@martuccelli2018]. En cambio, la sociología del individuo permite pluralizar el fenómeno y describir sus configuraciones concretas. Sobre esa base, adoptamos la siguiente definición que, si bien rescata la dimensiones del individualismo institucional, se aleja de pretensiones unívocas y se abre a potenciales variantes. 

De tal modo, se entenderá como individualismo al conjunto de concepciones que tratan a la persona como el responsable principal de su propia vida. Como tal, el individualismo define el lugar del individuo en la sociedad al (i) legitimar su acción en distintas esferas, (ii) sostener representaciones de mayor o menor independencia o interdependencia, y (iii) poniendo en relieve distintos valores predominantes, como la autonomía o la seguridad. 

A continuación, se definirán las principales dimensiones que emergen desde esta definición. 

## Legitimidad de la acción individual

La legitimidad de la acción individual hace referencia a las creencias sobre la agencia de los individuos en el mundo social [@brewer2007] y la legitimidad de acciones individualizadas en las esferas de la economía, la política y las emociones [@cortois2018]. Una mayor legitimidad de la acción individual se relaciona a una mayor valoración de la individualidad, la cual se define como el “grado de diferenciación o de singularización reconocido o legítimamente alcanzado por un individuo dentro de un colectivo” [@martuccelli2018]. 

<!-- Bajo el modelo del individualismo institucional, la individualidad deja de ser una anomalía para pasar a ostentar altos niveles de legitimidad (Martuccelli, 2018). Sin embargo, esto se vería tensionado, por ejemplo, por la acentuación de conductas individualizadas sin ruptura de lazos comunitarios en sociedades africanas, modelo que Martuccelli (2018) denomina como individualismo comunitario. Más cercano a la realidad nacional, Araujo y Martuccelli (2020b) constatan que la individualidad ha sido históricamente vista con sospecha en sociedades latinoamericanas. -->

El individualismo moderno ha sido institucionalizado principalmente en 3 esferas: la económica, la política y la afectiva [@cortois2018; @martuccelli2018]. En la esfera económica, el individualismo legitima la acción individual estratégica, poniendo los medios por sobre los fines. En cambio, en la esfera política, el individualismo se expresa como la obligación de tratar al otro como un fin en sí mismo. Por último, en la esfera afectiva, la acción individual se entiende como un medio para la expresión auténtica del yo [@cortois2018]. 

La hipótesis de esta artículo es que determinadas sociedades, o grupos de individuos dentro de estas, pueden legitimar la acción individual en algunas esferas, pero no necesariamente en otros. Por ejemplo, grupos conservadores podrían aceptar la acción individual en la esfera económica, pero no en la política o la afectiva. En cambio, grupos liberales podrían aceptar la acción individual en todas las esferas, pero con distintos grados de legitimidad.

## Representaciones culturales del Individuo

Son las diversas concepciones en torno a las que se pueden definir las identidades de los individuos en relación a sus grupos de referencia [@brewer2007]. Al respecto, es posible distinguir entre representaciones independientes, relacionales y colectivas [@brewer2007]. 

La representación independiente es aquella en que el individuo se concibe como un ente atomizado y prexistente a sus lazos sociales. Aunque esta concepción se ha considerado como propia de las culturas individualistas [@benavides2020; @cross2011], tal idea ha sido problematizada teórica [@voronov2002] y empíricamente  [@benavides2020; @kolstad2009]. Además, la persistencia de los llamados valores asiáticos en esas sociedades, que conceptualizan al individuo como inseparable de sus lazos sociales [@zhai2022], y la conceptualización de un híper-actor relacional en la sociedad chilena [@araujo2020a], sugieren la posibilidad de individualismos que difieren de las representaciones independientes.

De tal modo, se podrían identificar, además, representaciones relacionales y representaciones colectivas [@brewer2007]. En las primeras, la identidad del individuo se define por sus relaciones cercanas, tales como la familia o los amigos. En las segundas, en tanto, es la pertenencia a colectivos sociales más abstractos – esto es, grupos nacionales, regionales, étnicos o religiosos – lo que define a la identidad individual [@brewer2007].

La hipótesis de este artículo se alinea con las investigaciones de Kathya Aruajo y Danilo Martuccelli [-@araujo2012], que definen con al individualismo chileno como uno predominantemente relacional. Sin embargo, y en línea con las investigaciones sobre *self-construal* en la sociedad chilena [@benavides2020; @kolstad2009], se espera igualmente encontrar altos niveles de representaciones independientes.

## Valores

Por último, la tercera dimensión del individualismo se refiere a la importancia relativa que se le otorga en una sociedad a diversos valores e imperativos individuales o colectivos [@brewer2007], los cuales son producidos por procesos sociohistóricos de individuación [@martuccelli2018]. En el contexto del individualismo institucional, el principal valor para el individuo es la autonomía [@martuccelli2010], la que es promovida a través de un entramado institucional [@martuccelli2018] que promueve que los individuos se constituyen a sí mismos, planifiquen su propia vida y acepten la responsabilidad de si fracasan [@robles2001]. Es, pues, una individuación reflexiva en la que los individuos se definen por el imperativo de ejercer control de sus destinos y tomar decisiones de manera autónoma [@robles2001; @silvapalacios2015].

Sin embargo, también se han planteado visiones críticas a esta concepción, particularmente desde América Latina [@araujo2012; @robles2001]. No toda individuación sería reflexiva, ya que muchos individuos podrían experimentarla de forma delegativa, como una imposición [@silvapalacios2015]; no como un mundo de posibilidades, sino como uno lleno de incertidumbres. Los individuos, de tal modo, deben enfrentar las inseguridades ontológicas de la vida social a partir de sus propias habilidades bajo el imperativo de “arréglatelas como puedas” [@araujo2014; @robles2001]. Frente a esto, la valorización de la autonomía se desplaza por la búsqueda de seguridad como valor principal de esta forma de individuación [@silvapalacios2015].

La hipótesis de esta investigación es que en la sociedad chilena ha predominado una individuación delegativa que enfatiza valores como la seguridad por sobre la autonomía. No obstante, es posible que en grupos con mayores niveles de bienestar o estatus socioeconómico predomine una individuación reflexiva que enfatice la autonomía.  
